# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=10),
        ),
    ]
