# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 11:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pluto', '0002_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('value', models.TextField(max_length=512)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 3, 11, 1, 36, 591718, tzinfo=utc))),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 11, 1, 36, 591221, tzinfo=utc)),
        ),
    ]
