# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pluto', '0007_comment_rate_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='json',
            new_name='tilemap',
        ),
        migrations.AddField(
            model_name='level',
            name='command_backward',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='command_forward',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='command_left',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='command_lo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='command_op',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='command_right',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_to', to='pluto.Level'),
        ),
    ]
