# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluto', '0012_auto_20170902_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skin',
            field=models.CharField(default='polo', max_length=32),
        ),
    ]
